server:
  port: 8888
  servlet:
    context-path: /spring-boot
###配置jdbc的基本信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: java
###配置druid连接池的基本信息
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 3
      max-active: 30
      initial-size: 10
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
###配置thymeleaf信息      
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/view/
    suffix: .html
###配置mybatis信息
mybatis:
  mapper-locations: classpath*:/mapper/*.mapper.xml

